version: "3"
services:
    flaskapp:
        build:
            dockerfile: Dockerfile
            context: ./flask
        image: 'flaskapp:latest'
        container_name: flaskapp
        expose:
            - 8000

    nginx:
        build: ./nginx
        image: 'nginx:latest'
        container_name: nginx_c
        ports:
            - 8000:80
        depends_on:
            - flaskapp
            
